name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v4
        with:
          buildozer_version: latest
        env:
          PLATFORM: android
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
